#include "engine/operators/get_operator.hpp"
#include "engine/operators/projection_operator.hpp"
#include "engine/operators/aggregate_operator.hpp"
#include "engine/operators/filter_operator.hpp"
#include "engine/operators/csv_writer.hpp"